CREATE TYPE gender AS ENUM ('MALE', 'FEMALE');
CREATE TYPE kyc_status AS ENUM ('NONE', 'PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'BANNED', 'DELETED');
CREATE TYPE activity_status AS ENUM ('ACTIVE', 'INACTIVE', 'DELETED');
CREATE TYPE business_type AS ENUM ('INDIVIDUAL', 'COMMERCIAL');
CREATE TYPE week_day AS ENUM ('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN');