filebeat.inputs:
  - type: filestream
    id: modulith-logs
    enabled: true
    paths:
      - /app/logs/modulith*.log
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true
          expand_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "modulith-logs-%{+yyyy.MM.dd}"
  allow_older_versions: true

setup.ilm.enabled: false
setup.template.enabled: false

logging.level: warning
