networks:
  micro-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  elastic_data:
  redis_data:
  kafka_data:

services:

  # Postgres Database
  postgres:
    image: postgres:16-alpine
    container_name: postgres-tskhra
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups/keycloak_backup.sql:/docker-entrypoint-initdb.d/keycloak_backup.sql
    ports:
      - "5432:5432"
    networks:
      - micro-network


  # PgAdmin
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin-tskhra
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - micro-network


  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak-tskhra
    command: [ "-c", "/opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start-dev" ]
    entrypoint: /bin/sh
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak_db
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=password
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME=10.227.164.247 # add WORKS!
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-extensions/tskhra-theme:/opt/keycloak/themes/tskhra-theme
      - ./keycloak-extensions/providers/KeycloakUserRegistrationSpi-1.0-SNAPSHOT.jar:/opt/keycloak/providers/KeycloakUserRegistrationSpi-1.0-SNAPSHOT.jar
    depends_on:
      - postgres
    networks:
      - micro-network


  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis-tskhra
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - micro-network


  # RedisInsight
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-tskhra
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - micro-network


  # Modulith
  modulith:
    build: ./Modulith
    container_name: modulith-tskhra
    environment:
      - SERVER_PORT=8081
      - DB_HOST=postgres
      - DB_NAME=tskhra_db
      - KEYCLOAK_HOST=keycloak
      - MINIO_HOST=minio
      - REDIS_HOST=redis
      - KAFKA_HOST=kafka
    env_file:
      - ./Modulith/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - keycloak
      - minio
      - redis
    networks:
      - micro-network


  # Minio
  minio:
    image: minio/minio:latest
    container_name: minio-tskhra
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password

    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - micro-network


  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      # Runs ES as a single node to bypass cluster bootstrap checks
      - discovery.type=single-node
      - xpack.security.enabled=false
      # Limits memory usage so it doesn't crash your local machine
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - micro-network


  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      # Tells Kibana where to find Elasticsearch on the bridge network
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - micro-network


  #  Kafka
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      CLUSTER_ID: tskhra-cluster
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://10.227.164.247:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - micro-network


  # Kafka-UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: tskhra-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - micro-network
