server:
  port: ${SERVER_PORT:8081}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    deserialization:
      accept-float-as-int: false
  application:
    name: Modulith
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:tskhra_db}
    username: admin
    password: password # todo add to env + change
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://10.227.164.247:8080/realms/tskhra
          jwk-set-uri: http://keycloak:8080/realms/tskhra/protocol/openid-connect/certs # add WORKS!
  servlet:
    multipart:
      max-file-size: 5MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379


keycloak:
  server-url: http://${KEYCLOAK_HOST:localhost}:8080
  realm: tskhra
  client-id: user-service
  client-secret: hiDfHEHBRbi6VuEPvBDirMecSqINIXit # todo add to env

minio:
  url: http://${MINIO_HOST:localhost}:9000
  external-url: http://10.227.164.247:9000
  access-key: admin
  secret-key: password
  bucket-name: tskhra-images
  avatar-folder: user-avatars/
  business-folder: business-pictures/

rabbitmq:
  stomp:
    host: ${RABBITMQ_HOST:localhost}
    port: 61613
    login: admin
    passcode: password

sumsub:
  base-url: ${SUMSUB_BASE_URL:https://api.sumsub.com}
  secret-key: ${SUMSUB_SECRET_KEY}
  token: ${SUMSUB_TOKEN}
  level-name: ${SUMSUB_LEVEL_NAME}
