"""delete method field from PaymentDB model

Revision ID: 03925b9362d4
Revises: 7bd66ea0ca94
Create Date: 2026-04-16 06:47:18.604047

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03925b9362d4"
down_revision: Union[str, None] = "7bd66ea0ca94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "method")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("method", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
