"""rename product_id to entity_id and change int to str

Revision ID: 3c722a0e6695
Revises: 962612bf3c79
Create Date: 2026-04-15 11:59:37.187564

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c722a0e6695"
down_revision: Union[str, None] = "962612bf3c79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items", sa.Column("entity_id", sa.String(length=255), nullable=False)
    )
    op.drop_column("order_items", "product_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("order_items", "entity_id")
    # ### end Alembic commands ###
