"""add redirect_url to OrderItem model

Revision ID: 7bd66ea0ca94
Revises: 3c722a0e6695
Create Date: 2026-04-15 14:57:17.831525

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bd66ea0ca94"
down_revision: Union[str, None] = "3c722a0e6695"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("redirect_url", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "redirect_url")
    # ### end Alembic commands ###
